package generator

import (
	"bytes"
	"sort"
	"text/template"
)

var DefaultTemplate = `// Code generated by "go-genslice"; DO NOT EDIT.

package {{ .PackageName }}

{{ if eq .VarType "byte" -}}
var {{ .VarName }} = [][]{{ .VarType }}{
{{ range $i, $val := .Data}}	[]byte(`+"`"+`{{$val}}`+"`"+`), // {{$i}}
{{ end -}}
}
{{ end -}}

{{ if eq .VarType "string" -}}
var {{ .VarName }} = []{{ .VarType }}{
{{ range $i, $val := .Data}}	`+"`"+`{{$val}}`+"`"+`, // {{$i}}
{{ end -}}
}
{{ end -}}
`

type Config struct {
	Data        []string
	PackageName string
	VarType     string
	VarName     string
	Sort        bool
}

func GenerateCode(tpl string, config Config) ([]byte, error) {
	t, err := template.New("gen").Parse(tpl)
	if err != nil {
		return nil, err
	}

	if config.Sort {
		sort.Strings(config.Data)
	}

	var w bytes.Buffer
	err = t.Execute(&w, config)
	if err != nil {
		return nil, err
	}

	return w.Bytes(), nil
}
