package generator

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestGenerateCode(t *testing.T) {
	t.Run("byte", func(t *testing.T) {
		config := Config{
			PackageName: "test",
			VarType:     "byte",
			VarName:     "TestVar",
			Sort:        false,
			Data:        []string{"foo", "bar"},
		}
		result, err := GenerateCode(DefaultTemplate, config)
		assert.Nil(t, err)
		expected := []byte(`// Code generated by "go-genslice"; DO NOT EDIT.

package test

var TestVar = [][]byte{
	[]byte(`+"`"+`foo`+"`"+`), // 0
	[]byte(`+"`"+`bar`+"`"+`), // 1
}
`)
		assert.Equal(t, expected, result)
	})

	t.Run("string", func(t *testing.T) {
		config := Config{
			PackageName: "test",
			VarType:     "string",
			VarName:     "TestVar",
			Sort:        false,
			Data:        []string{"foo", "bar"},
		}
		result, err := GenerateCode(DefaultTemplate, config)
		assert.Nil(t, err)
		expected := []byte(`// Code generated by "go-genslice"; DO NOT EDIT.

package test

var TestVar = []string{
	`+"`"+`foo`+"`"+`, // 0
	`+"`"+`bar`+"`"+`, // 1
}
`)
		assert.Equal(t, expected, result)
	})
}
