name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v3.3.1
      with:
        go-version: ^1.15
      id: go

    - uses: actions/checkout@v3.5.3

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Test
      run: go test -v -cover ./...
    
    - name: Build
      run: go build -v
